version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: tinapa_cms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database_setup.sql:/docker-entrypoint-initdb.d/1-setup.sql
  app:
    build: .
    restart: always
    ports:
      - "80:80"
    environment:
      DB_DRIVER: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: tinapa_cms
    volumes:
      - .:/var/www/html
    depends_on:
      - db

volumes:
  db_data:

